# Generated by Django 2.1.15 on 2020-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0003_auto_20201006_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lente',
            old_name='marcas',
            new_name='marca',
        ),
        migrations.AlterField(
            model_name='lente',
            name='foto',
            field=models.CharField(max_length=255),
        ),
    ]
