# Generated by Django 2.1.15 on 2020-10-06 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0004_auto_20201006_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='idinventario',
            new_name='inventario',
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
